name: calnet
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - dask
  - dask-jobqueue
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - mlflow
  - pyyaml
  - zarr
  - psutil
  - ipykernel
